[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SERVICE_ID = "service_jrb3z4b"
  NEXT_PUBLIC_TEMPLATE_ID = "template_biywrha"
  NEXT_PUBLIC_EMAILJS_KEY = "1fXDxu7iY0dCslBVL"
  NODE_VERSION = "18.17.0"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["node_modules/@emailjs/browser/**/*"] 