name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: 'npm'
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Install dependencies
        run: npm ci
      
      - name: Verify environment variables
        run: |
          if [ -z "$NEXT_PUBLIC_SERVICE_ID" ]; then
            echo "Error: NEXT_PUBLIC_SERVICE_ID is not set"
            exit 1
          fi
          if [ -z "$NEXT_PUBLIC_TEMPLATE_ID" ]; then
            echo "Error: NEXT_PUBLIC_TEMPLATE_ID is not set"
            exit 1
          fi
          if [ -z "$NEXT_PUBLIC_EMAILJS_KEY" ]; then
            echo "Error: NEXT_PUBLIC_EMAILJS_KEY is not set"
            exit 1
          fi
        env:
          NEXT_PUBLIC_SERVICE_ID: ${{ secrets.NEXT_PUBLIC_SERVICE_ID }}
          NEXT_PUBLIC_TEMPLATE_ID: ${{ secrets.NEXT_PUBLIC_TEMPLATE_ID }}
          NEXT_PUBLIC_EMAILJS_KEY: ${{ secrets.NEXT_PUBLIC_EMAILJS_KEY }}
      
      - name: Build with Next.js
        run: npm run build
        env:
          NEXT_PUBLIC_SERVICE_ID: ${{ secrets.NEXT_PUBLIC_SERVICE_ID }}
          NEXT_PUBLIC_TEMPLATE_ID: ${{ secrets.NEXT_PUBLIC_TEMPLATE_ID }}
          NEXT_PUBLIC_EMAILJS_KEY: ${{ secrets.NEXT_PUBLIC_EMAILJS_KEY }}
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-site
          path: ./out
          retention-days: 1

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 5
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: nextjs-site
          path: ./out
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: out 